import asyncio
import contextlib
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import async_session_factory
from app.models.job import ScheduledJob
from app.models.user import User
from app.schemas.strategy import StrategyRunFilters, StrategyRunRequest
from app.services.scraper import create_scrape_job, execute_scrape_job

SCHEDULED_JOB_OWNER_CONFIG_KEY = "_created_by_user_id"

_scheduler_lock = asyncio.Lock()
_scheduler_task: asyncio.Task | None = None


@dataclass(frozen=True)
class ScheduledJobRunResult:
    job_id: int
    task_type: str
    status: str
    detail: str | None = None


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _parse_step(field: str, *, prefix: str = "*/") -> int | None:
    if not field.startswith(prefix):
        return None
    try:
        value = int(field.removeprefix(prefix))
    except ValueError:
        return None
    return value if value > 0 else None


def next_run_from_cron(cron_expression: str, *, after: datetime | None = None) -> datetime:
    """Return the next run for the simple cron patterns generated by the UI.

    Supported patterns:
    - 0 */N * * *  -> every N hours
    - 0 0 */N * *  -> every N days
    - 0 0 * * 1    -> weekly on Monday
    Unknown patterns conservatively fall back to one hour.
    """
    base = after or utcnow()
    if base.tzinfo is None:
        base = base.replace(tzinfo=timezone.utc)

    fields = cron_expression.split()
    if len(fields) != 5:
        return base + timedelta(hours=1)

    minute, hour, day_of_month, _month, day_of_week = fields

    if minute == "0" and (hours := _parse_step(hour)) is not None:
        return base + timedelta(hours=hours)

    if minute == "0" and hour == "0" and (days := _parse_step(day_of_month)) is not None:
        return base + timedelta(days=days)

    if minute == "0" and hour == "0" and day_of_month == "*" and day_of_week in {"1", "mon", "MON"}:
        days_until_monday = (7 - base.weekday()) % 7
        if days_until_monday == 0:
            days_until_monday = 7
        next_date = (base + timedelta(days=days_until_monday)).date()
        return datetime.combine(next_date, datetime.min.time(), tzinfo=timezone.utc)

    return base + timedelta(hours=1)


def scheduled_job_due(job: ScheduledJob, *, now: datetime | None = None) -> bool:
    if not job.enabled:
        return False
    if job.next_run is None:
        return False
    current = now or utcnow()
    if current.tzinfo is None:
        current = current.replace(tzinfo=timezone.utc)
    next_run = job.next_run if job.next_run.tzinfo else job.next_run.replace(tzinfo=timezone.utc)
    return next_run <= current


def stamp_created_by(config: dict | None, user_id: int) -> dict:
    stamped = dict(config or {})
    stamped.setdefault(SCHEDULED_JOB_OWNER_CONFIG_KEY, user_id)
    return stamped


async def initialize_next_run(db: AsyncSession, job: ScheduledJob, *, now: datetime | None = None) -> ScheduledJob:
    if job.next_run is None:
        job.next_run = next_run_from_cron(job.cron_expression, after=now or utcnow())
        await db.flush()
    return job


async def _run_scrape_job(db: AsyncSession, job: ScheduledJob) -> ScheduledJobRunResult:
    config = job.config or {}
    params = config.get("params") if isinstance(config.get("params"), dict) else dict(config)
    league = config.get("league") if isinstance(config.get("league"), str) else params.get("league")
    task_type = job.task_type or "scrape_odds"

    created = await create_scrape_job(db, task_type, league, params)
    await execute_scrape_job(db, created.id)
    return ScheduledJobRunResult(job_id=job.id, task_type=job.task_type, status="completed", detail=f"scrape_job:{created.id}")


async def _run_prediction_job(db: AsyncSession, job: ScheduledJob) -> ScheduledJobRunResult:
    # Imported lazily to avoid importing API routes during module import.
    from app.api.v1.strategies import run_strategy

    config = job.config or {}
    user_id = config.get(SCHEDULED_JOB_OWNER_CONFIG_KEY) or config.get("user_id")
    if not user_id:
        return ScheduledJobRunResult(job_id=job.id, task_type=job.task_type, status="skipped", detail="missing_user_id")

    user = await db.get(User, int(user_id))
    if user is None:
        return ScheduledJobRunResult(job_id=job.id, task_type=job.task_type, status="skipped", detail="missing_user")

    strategy_ids = [int(value) for value in config.get("strategy_ids") or []]
    if not strategy_ids:
        return ScheduledJobRunResult(job_id=job.id, task_type=job.task_type, status="skipped", detail="missing_strategy_ids")

    filters_payload = config.get("filters") if isinstance(config.get("filters"), dict) else {}
    request = StrategyRunRequest(
        match_ids=[int(value) for value in config.get("match_ids") or []],
        markets=list(config.get("markets") or []),
        filters=StrategyRunFilters(**filters_payload) if filters_payload else None,
        autopredict=True,
        avoid_reprediction=bool(config.get("avoid_reprediction", True)),
    )

    statuses: list[str] = []
    for strategy_id in strategy_ids:
        response = await run_strategy(strategy_id=strategy_id, body=request, db=db, user=user)
        statuses.append(f"{strategy_id}:{response.status}:{response.run_id}")

    return ScheduledJobRunResult(job_id=job.id, task_type=job.task_type, status="completed", detail=", ".join(statuses))


async def dispatch_scheduled_job(db: AsyncSession, job: ScheduledJob) -> ScheduledJobRunResult:
    task_type = (job.task_type or "").lower()
    if any(token in task_type for token in ("scrape", "odds", "world_cup_pipeline")):
        return await _run_scrape_job(db, job)
    if any(token in task_type for token in ("predict", "prediction", "strategy")):
        return await _run_prediction_job(db, job)
    return ScheduledJobRunResult(job_id=job.id, task_type=job.task_type, status="skipped", detail="unsupported_task_type")


async def run_due_scheduled_jobs(db: AsyncSession, *, now: datetime | None = None, limit: int = 10) -> list[ScheduledJobRunResult]:
    current = now or utcnow()
    async with _scheduler_lock:
        stmt = select(ScheduledJob).where(ScheduledJob.enabled.is_(True)).order_by(ScheduledJob.next_run.asc().nulls_last()).limit(limit)
        result = await db.execute(stmt)
        jobs = list(result.scalars().all())

        results: list[ScheduledJobRunResult] = []
        for job in jobs:
            if job.next_run is None:
                await initialize_next_run(db, job, now=current)
                results.append(ScheduledJobRunResult(job_id=job.id, task_type=job.task_type, status="scheduled", detail="initialized_next_run"))
                continue

            if not scheduled_job_due(job, now=current):
                continue

            try:
                run_result = await dispatch_scheduled_job(db, job)
            except Exception as exc:  # keep scheduler alive; surface failure in result
                run_result = ScheduledJobRunResult(job_id=job.id, task_type=job.task_type, status="failed", detail=str(exc))

            job.last_run = current
            job.next_run = next_run_from_cron(job.cron_expression, after=current)
            await db.flush()
            results.append(run_result)

        return results


async def scheduler_loop(*, interval_seconds: int = 60) -> None:
    while True:
        async with async_session_factory() as db:
            try:
                await run_due_scheduled_jobs(db)
                await db.commit()
            except Exception:
                await db.rollback()
        await asyncio.sleep(max(5, interval_seconds))


def start_scheduler(*, interval_seconds: int = 60) -> None:
    global _scheduler_task
    if _scheduler_task is None or _scheduler_task.done():
        _scheduler_task = asyncio.create_task(scheduler_loop(interval_seconds=interval_seconds))


async def stop_scheduler() -> None:
    global _scheduler_task
    if _scheduler_task is None:
        return
    _scheduler_task.cancel()
    with contextlib.suppress(asyncio.CancelledError):
        await _scheduler_task
    _scheduler_task = None
